// <auto-generated />
using System;
using Beispiel.Anwendung.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Beispiel.Anwendung.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Beispiel.Anwendung.Model.BaseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseProperty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BaseModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f4305bb-17ab-4a42-a1b2-f706573fa850"),
                            BaseProperty = "Base Property",
                            Description = "Base Description",
                            Name = "Base Name",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Beispiel.Anwendung.Model.Level2Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCondition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level2Property")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BaseId");

                    b.ToTable("Level2Models");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18262137-dd04-4977-93cf-f2698ae7d900"),
                            BaseId = new Guid("4f4305bb-17ab-4a42-a1b2-f706573fa850"),
                            Description = "Level2 Description",
                            IsCondition = true,
                            Level2Property = "Level2 Property",
                            Name = "Level2 Name",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Beispiel.Anwendung.Model.Level3Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Level2Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level3Property")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Level2Id");

                    b.ToTable("Level3Models");

                    b.HasData(
                        new
                        {
                            Id = new Guid("324cdcbf-6486-4e62-81c4-65196a6f52ca"),
                            Description = "Level3 Description",
                            Level2Id = new Guid("18262137-dd04-4977-93cf-f2698ae7d900"),
                            Level3Property = "Level3 Property",
                            Name = "Level3 Name",
                            Number = 42,
                            Status = 1
                        });
                });

            modelBuilder.Entity("Beispiel.Anwendung.Model.Level4Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Level2Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Level3Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level4Property")
                        .HasColumnType("TEXT");

                    b.Property<string>("ListProperty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Level2Id");

                    b.HasIndex("Level3Id");

                    b.ToTable("Level4Models");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f0cf5b8-9420-4441-ab6a-e25a78fd738e"),
                            Description = "Level4 Description",
                            Level2Id = new Guid("18262137-dd04-4977-93cf-f2698ae7d900"),
                            Level3Id = new Guid("324cdcbf-6486-4e62-81c4-65196a6f52ca"),
                            Level4Property = "Level4 Property",
                            ListProperty = "[\"Value 1\",\"Value 2\"]",
                            Name = "Level4 Name",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Beispiel.Anwendung.Model.Level2Model", b =>
                {
                    b.HasOne("Beispiel.Anwendung.Model.BaseModel", "Base")
                        .WithMany()
                        .HasForeignKey("BaseId");

                    b.Navigation("Base");
                });

            modelBuilder.Entity("Beispiel.Anwendung.Model.Level3Model", b =>
                {
                    b.HasOne("Beispiel.Anwendung.Model.Level2Model", "Level2")
                        .WithMany()
                        .HasForeignKey("Level2Id");

                    b.Navigation("Level2");
                });

            modelBuilder.Entity("Beispiel.Anwendung.Model.Level4Model", b =>
                {
                    b.HasOne("Beispiel.Anwendung.Model.Level2Model", "Level2")
                        .WithMany()
                        .HasForeignKey("Level2Id");

                    b.HasOne("Beispiel.Anwendung.Model.Level3Model", "Level3")
                        .WithMany()
                        .HasForeignKey("Level3Id");

                    b.Navigation("Level2");

                    b.Navigation("Level3");
                });
#pragma warning restore 612, 618
        }
    }
}
